apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   link.argocd.argoproj.io/external-link: spring-petclinic-service.default.svc.cluster.local
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
      annotations:
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: malston/spring-petclinic:2.5.0
