apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  labels:
    app: spring-petclinic-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: boot
  selector:
    app: spring-petclinic
  type: ClusterIP
