apiVersion: v1
kind: Service
metadata:
  name: kotlin-ktor-starter-service
  labels:
    app: kotlin-ktor-starter-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: boot
  selector:
    app: kotlin-ktor-starter
  type: ClusterIP
