apiVersion: v1
kind: Service
metadata:
  name: kotlin-sample-app-service
  labels:
    app: kotlin-sample-app-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: boot
  selector:
    app: kotlin-sample-app
  type: ClusterIP
