apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-ktor-starter
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: registry.pez.joecool.cc/kpack/kotlin-ktor-starter:b1.20210923.224636
        name: kotlin-ktor-starter
        ports:
        - containerPort: 8080
          protocol: TCP