apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 4
  template:
    spec:
      containers:
      - image: harbor.markalston.net/tanzu/spring-petclinic@sha256:da503c9f66161073e486194f8ced5897bb7a58ec5c7ca1838c758c6af2b8abba
        name: spring-petclinic
        ports:
        - containerPort: 8080
          protocol: TCP
